- name: Enable the rhel-{{ ansible_distribution_major_version }}-server-extras-rpms repository
  rhsm_repository:
    name: "rhel-{{ ansible_distribution_major_version }}-server-extras-rpms"
    state: present

- name: Install WALinuxAgent
  yum:
    name: WALinuxAgent
    state: latest

- name: Enable WALinuxAgent at boot
  service:
    name: waagent
    enabled: yes

- name: Copy ifcfg-eth0
  copy:
    src: files/ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0

- name: Copy network
  copy:
    src: files/network
    dest: /etc/sysconfig/network

- name: Configure SSH for Azure (1/2)
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "# Set Azure SSH settings."
    insertafter: EOF

- name: Configure SSH for Azure (2/2)
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "ClientAliveInterval 180"
    insertafter: EOF

- name: Enable swap on Resource Disk
  lineinfile:
    path: /etc/waagent.conf
    regexp: '^ResourceDisk\.EnableSwap='
    line: 'ResourceDisk\.EnableSwap=y'

- name: Set swap size for Resource Disk to 2GB
  lineinfile:
    path: /etc/waagent.conf
    regexp: '^ResourceDisk\.SwapSizeMB='
    line: 'ResourceDisk\.SwapSizeMB=2048'

- name: Disable grub splash screen for Azure (RHEL 6)
  lineinfile:
    path: /boot/grub/grub.conf
    backrefs: yes
    regex: '^\(splashimage=.*\)'
    line: '#\1'

- name : Remove rhgb kernel argument (RHEL 6)
  command: grubby --remove-args=rhgb --update-kernel=ALL
  when: ansible_distribution_major_version|int == 6

- name : Remove quiet kernel argument (RHEL 6)
  command: grubby --remove-args=quiet --update-kernel=ALL
  when: ansible_distribution_major_version|int == 6

- name: Add kernel arguments (RHEL 6)
  command: grubby --args="rootdelay=300 console=ttyS0 earlyprintk=ttyS0" --update-kernel=ALL
  when: ansible_distribution_major_version|int == 6

- name: Configure kernel arguments (RHEL 7)
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="crashkernel=auto rootdelay=300 console=ttyS0 earlyprintk=ttyS0 net.ifnames=0"'
  when: ansible_distribution_major_version|int == 7

- name: Rebuild grub config (RHEL 7)
  command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_distribution_major_version|int == 7

- name: Remove udev persistent network rule generator
  file:
    path: /etc/udev/rules.d/75-persistent-net-generator.rules
    state: absent

- name: Link udev persistent network rule generator to /dev/null
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/75-persistent-net-generator.rules
    state: link

- name: Lock root account
  user:
    name: root
    password: "!!"
