---
- hosts: all
  gather_facts: true
  tasks:
    #- debug: var=hostvars

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Azure specific role
      include_role:
        name: Azure
      when: ansible_virtualization_type == "VirtualPC"

    - name: GCP specific role
      include_role:
        name: GCP
      when: ansible_virtualization_type == "kvm"

    - name: VMware specific role
      include_role:
        name: VMware
      when: ansible_virtualization_type == "VMware"

    - name: Common role
      include_role:
        name: Common
